version: '2'

services:
  tags-service:
    image: 'tags-service:latest'
    build:
      context: .
    container_name: tags-service
    depends_on:
      - cards-service
      - db-tags
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-tags:5433/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"
  cards-service:
    image: 'vlmaier/cards-service:0.0.1-SNAPSHOT'
    container_name: cards-service
    depends_on:
      - db-cards
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-cards:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db-cards:
    image: 'postgres:15.1-alpine'
    container_name: db-cards
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  db-tags:
    image: 'postgres:15.1-alpine'
    container_name: db-tags
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
